#!/usr/bin/env ts-node
/**
 * CLI: compile the Shannon's Demon strategy-overview PDF.
 * Usage: ts-node src/strategy-deck.ts [--keep-tex] [--no-charts]
 *
 * Outputs:
 *   data/reports/strategy-deck.tex
 *   data/reports/strategy-deck.pdf
 *   data/reports/charts/*.png  (generated by Python if missing)
 */

import * as fs   from 'fs';
import * as path from 'path';
import { execSync, ExecSyncOptionsWithBufferEncoding } from 'child_process';
import { buildStrategyDeck } from './latex-strategy';

// ── Paths ─────────────────────────────────────────────────────────────────────
const SCRIPT_DIR   = __dirname;
const REPORTING_DIR = path.resolve(SCRIPT_DIR, '..');          // reporting/
const REPO_ROOT    = path.resolve(REPORTING_DIR, '..');        // repo root
const REPORTS_DIR  = path.join(REPO_ROOT, 'data', 'reports');
const CHARTS_DIR   = path.join(REPORTS_DIR, 'charts');
const TEX_PATH     = path.join(REPORTS_DIR, 'strategy-deck.tex');
const PDF_PATH     = path.join(REPORTS_DIR, 'strategy-deck.pdf');

// ── Args ──────────────────────────────────────────────────────────────────────
const args      = process.argv.slice(2);
const keepTex   = args.includes('--keep-tex');
const noCharts  = args.includes('--no-charts');

const EXEC_OPTS: ExecSyncOptionsWithBufferEncoding = { encoding: 'buffer' };

// ── Helpers ───────────────────────────────────────────────────────────────────
function run(cmd: string, cwd?: string): void {
  const opts = cwd ? { ...EXEC_OPTS, cwd } : EXEC_OPTS;
  execSync(cmd, opts);
}

function which(cmd: string): boolean {
  try { execSync(`which ${cmd}`, { stdio: 'pipe' }); return true; }
  catch { return false; }
}

function ensureCharts(): void {
  const needed = ['chart_performance.png', 'chart_drawdown.png', 'chart_monthly_heatmap.png'];
  const missing = needed.some(f => !fs.existsSync(path.join(CHARTS_DIR, f)));

  if (!missing) {
    console.log('Charts: all present, skipping generation.');
    return;
  }

  const py = which('python3') ? 'python3' : which('python') ? 'python' : null;
  if (!py) {
    console.error('WARNING: Python not found; charts will be missing from the PDF.');
    return;
  }

  const genScript = path.join(REPO_ROOT, 'backtest', 'generate_charts.py');
  if (!fs.existsSync(genScript)) {
    console.error(`WARNING: ${genScript} not found; charts will be missing.`);
    return;
  }

  console.log('Generating charts...');
  try {
    const out = execSync(`${py} "${genScript}"`, { ...EXEC_OPTS, cwd: REPO_ROOT });
    process.stdout.write(out);
  } catch (err: any) {
    process.stderr.write(err.stdout ?? Buffer.alloc(0));
    process.stderr.write(err.stderr ?? Buffer.alloc(0));
    console.error('WARNING: Chart generation failed; PDF will be missing images.');
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────
function main(): void {
  fs.mkdirSync(REPORTS_DIR, { recursive: true });
  fs.mkdirSync(CHARTS_DIR,  { recursive: true });

  // Step 1 — generate charts
  if (!noCharts) ensureCharts();

  // Step 2 — build LaTeX source
  console.log('Building LaTeX source...');
  const tex = buildStrategyDeck();
  fs.writeFileSync(TEX_PATH, tex, 'utf-8');
  console.log(`  Written: ${path.relative(REPO_ROOT, TEX_PATH)}`);

  // Step 3 — detect pdflatex
  const latex = which('pdflatex') ? 'pdflatex'
              : which('latexmk')  ? 'latexmk'
              : null;

  if (!latex) {
    console.error('\nERROR: pdflatex not found.');
    console.error('Install with:');
    console.error('  sudo apt-get install texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra');
    console.error(`\nThe .tex file has been written to ${TEX_PATH}`);
    console.error('You can compile it manually: cd data/reports && pdflatex strategy-deck.tex');
    process.exit(1);
  }

  // Step 4 — compile (two passes for cross-references)
  const pdflatexCmd = `pdflatex -interaction=nonstopmode -halt-on-error strategy-deck.tex`;
  const latexmkCmd  = `latexmk -pdf -interaction=nonstopmode strategy-deck.tex`;
  const compileCmd  = latex === 'latexmk' ? latexmkCmd : pdflatexCmd;

  for (let pass = 1; pass <= (latex === 'pdflatex' ? 2 : 1); pass++) {
    console.log(`Compiling pass ${pass}${latex === 'pdflatex' ? '/2' : ''}...`);
    try {
      run(compileCmd, REPORTS_DIR);
    } catch (err: any) {
      process.stderr.write(err.stdout ?? Buffer.alloc(0));
      process.stderr.write(err.stderr ?? Buffer.alloc(0));
      console.error('\nLaTeX compilation failed.');
      console.error(`Check the log at ${path.join(REPORTS_DIR, 'strategy-deck.log')}`);
      process.exit(1);
    }
  }

  // Step 5 — cleanup aux files
  const auxExts = ['aux', 'log', 'nav', 'out', 'snm', 'toc', 'fls', 'fdb_latexmk'];
  for (const ext of auxExts) {
    const f = path.join(REPORTS_DIR, `strategy-deck.${ext}`);
    if (fs.existsSync(f)) fs.unlinkSync(f);
  }

  // Step 6 — optionally remove .tex
  if (!keepTex && fs.existsSync(TEX_PATH)) {
    fs.unlinkSync(TEX_PATH);
    console.log('  Removed .tex (pass --keep-tex to retain it)');
  }

  const size = fs.statSync(PDF_PATH).size;
  console.log(`\n  PDF: ${path.relative(REPO_ROOT, PDF_PATH)}  (${(size / 1024).toFixed(0)} KB)`);
}

main();
